spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jss
    username: dbuser
    password: kullanicisifree
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

    
